openapi: "3.0.0"
info:
  version: 0.0.1
  title: Orders
paths:
  /apis/orders:
    get:
      summary: 특정 유저의 모든 주문내역을 조회합니다.
      operationId: showAllOrdersByUsers
      tags:
        - order
      parameters:
        - in: query
          name: v
          schema:
            type: string
            example: '0.0.2'
          description: The version of api
        - in: query
          name: user
          schema:
            type: string
            example: '123456-2222123'
          description: "user name"
        - in: query
          name: detail
          schema:
            type: string
            example: '얼굴이 동그라미'
          description: "user detail"
      responses:
        '200':
          description: 모든 주문 내역을 반환 합니다.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubscriptionOrdersModel'
        '400':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    SubscriptionOrdersModel:
      type: 'object'
      properties:
        id:
          type: 'string'
          description: 'orderId'
          example: '246523764'
        subscriptionId:
          type: 'string'
          description: '정기 결제가 진행된 구독 ID 입니다'
          example: 'ad4d8bed-1967-4e68-af97-290ca710c2f6_3647777233'
        result:
          type: 'string'
          example: "SUCCESS | FAILED"
          description: '여부 실패시, additionalProperties 에 failedReason 포함됨'
        userId:
          type: 'string'
          example: 'ad4d8bed-1967-4e68-af97-290ca710c2f6'
        orderId:
          type: 'string'
          example: 'order-2312355'
          description: 'PG 에서 확인할 수 있는 고유 결제 ID'
        paidAt:
          type: 'string'
          example: "2022-08-11"
          description: '결제일을 확인할 수 있다.'
        refundedAt:
          type: 'string'
          example: "2022-08-09"
          description: '결제일을 확인할 수 있다.'
        additionalProperties:
          additionalProperties:
            $ref: '#/components/schemas/StringMap'
          type: object
          description: '추가 되어질 수 있는 내역 담기'
    Error:
      required:
        - value
      properties:
        description:
          type: 'string'
          example: '적절하지 않은 값입니다.'
    StringMap:
      type: string
